language: java
before_install:
- git clone https://github.com/pointbazaar/dragon-lexer
- cd dragon-lexer/src
- sudo ./build.sh
- cd ../..
- git clone https://github.com/pointbazaar/dragon-parser
- cd dragon-parser
- mvn install -DskipTests
- cd ..
install: mvn install
