os: linux
dist: focal #default dist, distro matrix is in 'jobs'
#arch:
#  - amd64
#  - arm64

compiler: gcc
language: c

jobs:
  include: 
    - dist: focal # 20.04
      arch: amd64
    
    - dist: focal
      arch: arm64

    - dist: bionic # 18.04
      arch: amd64

    - dist: bionic
      arch: arm64

    - dist: xenial # 16.04
      arch: amd64

    - dist: xenial
      arch: arm64

before_install:
- pwd
- cd .
addons:
  apt:
    packages:
      - valgrind
      #- gcc-9 #people can bring their own gcc whatever version. 
      #don't even care anymore.
install: pwd
script: make all_no_valgrind
env:
- export PATH=$PATH:$(pwd):$(pwd)/lexer:$(pwd)/parser
