language: c
os: linux
before_install:
- pwd
- cd .
#- sudo apt-get install -y valgrind
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - valgrind
      - gcc-10
install: pwd
script: make
env:
- export PATH=$PATH:$(pwd):$(pwd)/lexer:$(pwd)/parser
