os: linux
arch:
  - amd64
  - arm

language: c
jobs:
  include: 
    - dist: focal
    - dist: xenial

before_install:
- pwd
- cd .
addons:
  apt:
    packages:
      - valgrind
      - gcc-10
install: pwd
script: make
env:
- export PATH=$PATH:$(pwd):$(pwd)/lexer:$(pwd)/parser
