os: linux
dist: focal #default dist, distro matrix is in 'jobs'

compiler: gcc
language: c

jobs:
  include: 
    - dist: focal # 20.04
      arch: amd64
    
    - dist: focal
      arch: arm64

    - dist: bionic # 18.04
      arch: amd64

    - dist: bionic
      arch: arm64

    - dist: xenial # 16.04
      arch: amd64

    - dist: xenial
      arch: arm64
    
    - dist: trusty # 14.04
      arch: amd64
 
    - dist: trusty
      arch: arm64
    
    # their gcc does not have --std=c11
    #- dist: precise # 12.04
    #  arch: amd64

    #- dist: precise
    #  arch: arm64

before_install:
- pwd
- cd .
addons:
  apt:
    packages:
      - valgrind
install: pwd
script: make all_no_valgrind
env:
- export PATH=$PATH:$(pwd):$(pwd)/lexer:$(pwd)/parser
