os: linux
arch:
  - amd64
  - arm64
dist:
  - focal
  - bionic
  - xenial
language: c
#jobs:
#  include: 
#    - dist: focal # 20.04
#    - dist: bionic # 18.04
#    - dist: xenial # 16.04

before_install:
- pwd
- cd .
addons:
  apt:
    packages:
      - valgrind
      - gcc-9
install: pwd
script: make
env:
- export PATH=$PATH:$(pwd):$(pwd)/lexer:$(pwd)/parser
