version: 2.1

jobs:
  build:
    #docker:
    #  - image: gcc:9.3.0
    machine:
      # i want to use a machine image instead of a docker container
      # because i need root access to install packages
      image: ubuntu-1604:201903-01 # Ubuntu 16.04
      #image: ubuntu-2004:202008-01 # Ubuntu 20.04 # this lacks even most basic utilities
    environment:
      PATH: $PATH:$(pwd):$(pwd)/lexer:$(pwd)/parser
    steps:
      - run: sudo apt-get update
      - run: sudo apt install -y gcc valgrind make
      - checkout
      - run: make 

# Orchestrate or schedule a set of jobs
workflows:
  version: 2
  # Name the workflow "welcome"
  #welcome:
    # Run the welcome/run job in its own container
    #jobs:
      #- welcome/run
  build_and_test:
    jobs:
      - build
