version: 2.1

# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1


jobs:
  build:
    #docker:
    #  - image: gcc:9.3.0
    machine:
      #image: ubuntu-1604:201903-01 # # recommended linux image - includes Ubuntu 16.04
      image: ubuntu-2004:202008-01 # ubuntu 20.04
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt install -y gcc valgrind make
      - run: make 

# Orchestrate or schedule a set of jobs
workflows:
  version: 2
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
  build_and_test:
    jobs:
      - build
